site_name: CBT

nav:
    - Home: index.md
    - Functions:
        - Simple:
            - F1: 2arg_func_call_evaluation_args.md
            - F2: f2_3args.md
    - Lists:
        - Introduction: lists.md
        - L1: 2arg_func_call.md